rule("lex")
  set_extensions(".l")
  on_build(function(target,sourcefile)
    print(path.basename(sourcefile))
    -- os.execute("lex -o "..target.." "..sourcefile)
  end)
rule("yacc")
  set_extensions(".y")
  on_build(function(target,sourcefile)
    -- os.execute("bison -d -o "..sourcefile)
  end)
target("minus-fb")
  set_targetdir(".")
  
  add_rules("lex","yacc")
  add_files("minus.l")
  add_files("minus.y")
  add_files("*.c")